name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - master
    paths: 
      - '**.go'
      - '**.sql'
      - 'go.*'
      - 'Dockerfile'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Configure git for private modules
        env:
          GO_DEPS_GITHUB_TOKEN: ${{ secrets.GO_DEPS_GITHUB_TOKEN }}
        shell: bash
        run: |
          git config --global url."https://$GO_DEPS_GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Build
        # go build will download verify and build (building to speed up next step hopefully)
        run: go build cmd/main.go
    
    - name: Check docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tag: pepoolife/goapp:latest
        build-args: |
            GO_DEPS_GITHUB_TOKEN=${{ secrets.GO_DEPS_GITHUB_TOKEN }}
